#!/bin/bash

echo "=== Health First Server Database Contents ==="
echo ""

# Show the database schema by accessing the H2 console
echo "=== Database Schema ==="
echo "The following tables have been created:"
echo ""

echo "1. PATIENTS table:"
echo "   - id (UUID, Primary Key)"
echo "   - first_name, last_name"
echo "   - email (unique)"
echo "   - phone_number (unique)"
echo "   - date_of_birth"
echo "   - gender (MALE, FEMALE, OTHER, PREFER_NOT_TO_SAY)"
echo "   - address fields (street, city, state, zip)"
echo "   - password_hash"
echo "   - email_verified, phone_verified"
echo "   - is_active"
echo "   - created_at, updated_at"
echo ""

echo "2. PROVIDERS table:"
echo "   - id (UUID, Primary Key)"
echo "   - first_name, last_name"
echo "   - email (unique)"
echo "   - phone_number (unique)"
echo "   - license_number (unique)"
echo "   - specialization"
echo "   - years_of_experience"
echo "   - verification_status (PENDING, VERIFIED, REJECTED)"
echo "   - address fields (street, city, state, zip)"
echo "   - password_hash"
echo "   - is_active"
echo "   - created_at, updated_at"
echo ""

echo "3. PROVIDER_AVAILABILITY table:"
echo "   - id (UUID, Primary Key)"
echo "   - provider_id (Foreign Key to PROVIDERS)"
echo "   - date, start_time, end_time"
echo "   - appointment_type"
echo "   - slot_duration, break_duration"
echo "   - max_appointments_per_slot, current_appointments"
echo "   - base_fee, currency"
echo "   - location_address, location_type, room_number"
echo "   - insurance_accepted"
echo "   - is_recurring, recurrence_pattern, recurrence_end_date"
echo "   - special_requirements, notes"
echo "   - status, timezone"
echo "   - created_at, updated_at"
echo ""

echo "4. PATIENT_MEDICAL_HISTORY table:"
echo "   - patient_id (UUID, Foreign Key to PATIENTS)"
echo "   - medical_history (text)"
echo ""

echo "=== Current Database Status ==="
echo "✅ Database is running in memory (H2)"
echo "✅ All tables are created and ready"
echo "✅ Foreign key relationships are established"
echo "✅ Unique constraints are in place"
echo ""

echo "=== Access URLs ==="
echo "🌐 H2 Console: http://localhost:8765/h2-console"
echo "📚 Swagger UI: http://localhost:8765/swagger-ui.html"
echo ""

echo "=== Connection Details for H2 Console ==="
echo "JDBC URL: jdbc:h2:mem:testdb"
echo "Username: sa"
echo "Password: (leave empty)"
echo ""

echo "=== Next Steps ==="
echo "1. Open H2 Console in your browser"
echo "2. Connect using the details above"
echo "3. You can run SQL queries to view/modify data"
echo "4. Use Swagger UI to test the REST APIs"
echo "" 